### ISSUE TITLE
random crash due to nodejs memory limit

### ISSUE THREAD

**Issue by Dradallor** [koktaildotcom/node-p1-reader#1]
Hi All,

First off thanks for putting this out there. It works as you would expect.
I found a small issue with the node-p1-reader however when it's running on a Pi Model B.

Every 5 minutes it will run out of memory, which is to be expected with the limited RAM in the Model B.
A quick solution for this is following the same config procedure but instead of running it at npn examples/example.js is to first install NPN Forever, (https://www.npmjs.com/package/forever)

```
npm install forever -g
forever start examples/example.js
```

This would run the script in the forever monitor and once the RAM stack is overloaded it will restart the script for you. Instead of running it as a Forever directly you could setup forever-monitor in the script as well but that doesn't really seem necessary with a simple additional instruction.

Regards,
Mike

**Comment by koktaildotcom** [comment]
@Dradallor that is good to hear, did't work for me because i have an older smartmeter with DSMR 3.0.
Thanks for the tip of the `forever` package. Did you know why it is consuming that much RAM?

**Comment by koktaildotcom** [comment]
I've transferred the issue to `/koktaildotcom/node-p1-reader` because thats the package what caused it. I have forked the repository and add the call to the Homey `com.p1.smartmeter app` because the majority of the people uses DSMR 4.0. (i use a different package for DSMR 3.0).

I'll leave the issue open for other people to read.

**Comment by pro-sumer** [comment]
I added `--max-old-space-size` in the Node.js script invocation (with value `256` for now), as suggested [here](https://github.com/nodejs/node/issues/2738).

My [Raspberry Pi Zero W](https://www.raspberrypi.org/products/raspberry-pi-zero-w/) was locking up without that. So far, it no longer stalls, but the `node` process does still consume more than 90% of the CPU all the time.

Is this supposed to happen? (Is the Zero capable enough for this?)

**Comment by koktaildotcom** [comment]
You all can try this: 

I updated my app com.p1 for reading out your smartmeter. The app has an new implementation of the script that pushes the data to homey. The push script is almost real-time and uses less CPU and mem (@RP3  mem:  4 MB    CPU: 10% ). Due to incompatibility there is an new driver. The current one is deprecated and will be removed after some time.

The app in test: https://homey.app/a/com.p1/test/
The pusher script: https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader
