### ISSUE TITLE
[bug] Sporadically incorrect total gas consumption

### ISSUE THREAD

**Issue by lucasvdh** [koktaildotcom/node-p1-reader#3]
# Sporadically incorrect total gas consumption

Every x amount of time (once a day/every few days) the P1 reader will report an incorrect amount for the total gas consumption.

## Error
The deviation is usually between 20 and 21 m3 less then what is to be expected. This deviation only happens for one tick and then it jumps back to the correct value again. 

Maybe it's some weird rounding error?

## Examples
Example of this case in Homey Insights:

![image](https://user-images.githubusercontent.com/4311594/62525666-15818580-b838-11e9-9f1a-c446e51b0014.png)

Corresponding data:

Datetime | Total gas consumption m3
-- | --
2019-08-06 03:15:00 | 1228.76
2019-08-06 03:20:00 | 1228.76
2019-08-06 03:25:00 | 1228.76
2019-08-06 03:30:00 | 1228.76
2019-08-06 03:35:00 | 1208.28066666667
2019-08-06 03:40:00 | 1228.76
2019-08-06 03:45:00 | 1228.76016666667
2019-08-06 03:50:00 | 1228.77
2019-08-06 03:55:00 | 1228.77

**Comment by koktaildotcom** [comment]
I think this is resolved when using the new pusher script:

I updated my app com.p1 for reading out your smartmeter. The app has an new implementation of the script that pushes the data to homey. The push script is almost real-time and uses less CPU and mem (@RP3  mem:  4 MB    CPU: 10% ). Due to incompatibility there is an new driver. The current one is deprecated and will be removed after some time.

The app in test: https://homey.app/a/com.p1/test/
The pusher script: https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader
